// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa51ap5I3m6YgY_yMjEgymvyCQ1BYH0N8',
    appId: '1:437890251773:web:1dabb322f8b847f6d9f794',
    messagingSenderId: '437890251773',
    projectId: 'bookswap-45248',
    authDomain: 'bookswap-45248.firebaseapp.com',
    storageBucket: 'bookswap-45248.firebasestorage.app',
    measurementId: 'G-WM714ZT6SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWAm1ClTtXFreKRi0mB4r8KpMM51MC3aw',
    appId: '1:437890251773:android:043006adc31a2645d9f794',
    messagingSenderId: '437890251773',
    projectId: 'bookswap-45248',
    storageBucket: 'bookswap-45248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbteOIHn5BIBdxJnyySXFYi_3Pfl060ts',
    appId: '1:437890251773:ios:c1691c588e7e0e71d9f794',
    messagingSenderId: '437890251773',
    projectId: 'bookswap-45248',
    storageBucket: 'bookswap-45248.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbteOIHn5BIBdxJnyySXFYi_3Pfl060ts',
    appId: '1:437890251773:ios:c1691c588e7e0e71d9f794',
    messagingSenderId: '437890251773',
    projectId: 'bookswap-45248',
    storageBucket: 'bookswap-45248.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa51ap5I3m6YgY_yMjEgymvyCQ1BYH0N8',
    appId: '1:437890251773:web:6e7a3e0c402bf7add9f794',
    messagingSenderId: '437890251773',
    projectId: 'bookswap-45248',
    authDomain: 'bookswap-45248.firebaseapp.com',
    storageBucket: 'bookswap-45248.firebasestorage.app',
    measurementId: 'G-P8J5N94J1V',
  );
}
